apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  project: default
  source:
    path: helm-chart
    repoURL:  'https://github.com/vjkancherla/github-actions'
    helm:
      valueFiles:
        - namespaces/prod/values.yaml
        - namespaces/prod/version.yaml
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
