name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Git commit hash short
        id: git_hash_calc_step
        run: |
          echo "git_hash_short=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run Super-Linter
        uses: github/super-linter@v5
        continue-on-error: true
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:${{ steps.git_hash_calc_step.outputs.git_hash_short }}

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:${{ steps.git_hash_calc_step.outputs.git_hash_short }}
          dockerfile: ./Dockerfile

      - run: echo "🍏 This job's status is ${{ job.status }}."
